-- 2HOL Town Hall Database Schema

-- Coords Table
CREATE TABLE IF NOT EXISTS coords (
  id SERIAL PRIMARY KEY,
  type VARCHAR(100) NOT NULL,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  notes TEXT,
  status VARCHAR(50) DEFAULT 'Active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Notices Table
CREATE TABLE IF NOT EXISTS notices (
  id SERIAL PRIMARY KEY,
  message TEXT NOT NULL,
  priority VARCHAR(20) DEFAULT 'Normal',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Tasks Table
CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  status VARCHAR(20) DEFAULT 'Open',
  claimed_by VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
